// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xivmkhdgeicmntlffatr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpdm1raGRnZWljbW50bGZmYXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjA1MDQsImV4cCI6MjA2MTk5NjUwNH0.crA0EyrIz7VKYmYb_Xv37-5oxR4tFOTh74oKI4oOl4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);